site_name: lawcite
site_description: Tools for translating Danish laws to BibTeX format for citing.
site_author: evid
site_url: https://evidlabel.github.io/lawcite/
repo_url: https://github.com/evidlabel/lawcite
theme:
  name: material
  palette:
    primary: orange
    scheme: slate
  features:
    - content.code.copy
  font:
    text: Ubuntu
    code: Ubuntu Mono


nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

  - pymdownx.tabbed:
      alternate_style: true
