name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install UV
      run: |
        pip install uv

    - name: Create virtual environment
      run: uv venv .venv

    - name: Install dependencies
      run: |
        uv pip install .[dev]

    - name: Run tests
      run: |
        uv run pytest  # Fixed to run pytest via uv to ensure it's in the environment
